auto scroll can be disabled with 'Z' * auto scroll can be disabled/enabled by pressing 'Z' (like in LoL) * projectile loses focus when moving a figure (clients only lose focus when own figure is moved) * client object remembers associated team
@ohcibi Is there a way (except for re-cloning) to fix this?:
error: object file .git/objects/24/aecbd1d5ba62d0a7e19f764e43e1a2f172dcc5 is empty
fatal: loose object 24aecbd1d5ba62d0a7e19f764e43e1a2f172dcc5 (stored in .git/objects/24/aecbd1d5ba62d0a7e19f764e43e1a2f172dcc5) is corrupt